GET http://localhost:9005/api/blogs HTTP/1.1

###
GET http://localhost:9005/api/blogs/4 HTTP/1.1

###
DELETE http://localhost:9005/api/blogs/3 HTTP/1.1

###
POST http://localhost:9005/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: bearer token

{
    "title": "The revolution of the Web 4",
    "url": "http://blog.com/intro-psql",
    "author": "Posix CET",
    "likes": 4,
    "year": 2022
}

###
PUT http://localhost:9005/api/blogs/5 HTTP/1.1
Content-Type: application/json

{
    "likes": "2"
}

###
GET http://localhost:9005/api/users HTTP/1.1

###

GET http://localhost:9005/api/users/1 HTTP/1.1

###
POST http://localhost:9005/api/users HTTP/1.1
Content-Type: application/json

{
    "username": "ashirafumiiro@gmail.com",
    "name": "Ashirafu Miiro"
}

###
POST http://localhost:9005/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "posix@gmail.com",
    "password": "secret"
}

###

###
PUT http://localhost:9005/api/users/ashirafumiiro2 HTTP/1.1
Content-Type: application/json

{
    "username": "ashirafumiiro"
}

###
GET http://localhost:9005/api/authors HTTP/1.1

###
POST http://localhost:9005/api/readinglists HTTP/1.1
Content-Type: application/json

{
    "userId": "1",
    "blogId": "1"
}

