apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/persistentvolume.yaml
  - manifests/postgres-deployment.yaml
  - manifests/blogs-deployment.yaml

images:
  - name: ashirafumiiro/blogs-dep
    newName: ashirafumiiro/blogs-dep